$lock_cmd = qs -c $qsConfig ipc call lock activate
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    inhibit_sleep = 3
}

# 1. Bloquear a sessão (29 minutos)
listener {
    timeout = 1740
    on-timeout = loginctl lock-session
}

# 2. Apagar a tela (30 minutos)
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 3. Suspender o sistema (40 minutos)
listener {
    timeout = 2400
    on-timeout = $suspend_cmd
}
